package site.aoba.jobanalyzer.components;

import lombok.extern.slf4j.Slf4j;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Async;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import site.aoba.jobanalyzer.models.ViewHistory;
import site.aoba.jobanalyzer.services.KafkaSendService;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Random;

@Slf4j
@Component
public class DataGeneratorComponent {
    private final KafkaSendService kafkaSendService;
    private final Random random = new Random();
    private final Calendar startMonth;

    @Autowired
    public DataGeneratorComponent(KafkaSendService kafkaSendService) {
        this.kafkaSendService = kafkaSendService;
        this.startMonth = new GregorianCalendar();
        this.startMonth.set(2010, 1, 1);
    }

    @Scheduled(cron = "0 */5 * ? * ?")
    @Async
    public void autoGenerateData() {
        int clickTimes = random.nextInt(3000) + 1000;
        log.info("{} {}", startMonth, clickTimes);
        for (int i = 0; i < clickTimes; i++) {
            int currentClicked = random.nextInt(1217) + 1;
            ViewHistory viewHistory = new ViewHistory();
            viewHistory.setDate(startMonth.getTime());
            viewHistory.setJobId(currentClicked);
            kafkaSendService.sendMessage(viewHistory);
        }
        this.startMonth.add(Calendar.MONTH, 1);
    }
}
